services:
  api:
    build:
      context: .   # current folder, not ./backend
      dockerfile: Dockerfile
    container_name: portfolio_api
    ports:
      - "8000:8000"
    env_file:
      - ./.env    # current folder
    environment:
      - ENVIRONMENT=development
    networks:
      - portfolio_network

networks:
  portfolio_network:
    driver: bridge
